networks:
  appnet:

volumes:
  appvol:

services:
  mydb:
    image: stackupiss/northwind-db:v1
    volumes:
    - appvol:/var/lib/mysql
    networks:
    - appnet
  
  myapp:
    image: stackupiss/northwind-app:v1
    networks:
    - appnet
    ports:
    - 8000-9000:3000
    environment:
    - DB_HOST=mydb
    - DB_USER=root
    - DB_PASSWORD=changeit